server:
  port: 9002

# setting for mysql server
spring:
  datasource:
    url : jdbc:mysql://localhost:3306/microservice2?useSSl=false
    username: root
    password: Toor@123456
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: update
        show-sql: true
