server:
  port: 9004



#register with eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost


#routing configuration:
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
      - id: USER-SERVICE
        uri: lb://USER-SERVICE
        predicates:
          - Path=/user/**
        filters:
          - name: CircuitBreaker
            args:
              name: USER-SERVICE
              fallbackuri: forward:/userfallback
      - id: DEPARTMENT-SERVICE
        uri: lb://DEPARTMENT-SERVICE
        predicates:
          - Path=/department/**
        filters:
          - name: CircuitBreaker
            args:
              name: DEPARTMENT-SERVICE
              fallbackuri: forward:/departmentfallback

#Circuit Breaker
# It will identify which services are not working then it will run the fallback method available
# and it will notify user as this services is not running
# we ll implementing "Hystrix Library" and "Hystrix Dashboard". we can identify which services is running or not.

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000


# configuration for the actuator
# it is enabling the hystrix.stream. it can use the information in hystrix dashboard
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream