server:
  port: 9001

# setting for mysql server
spring:
  datasource:
    url : jdbc:mysql://localhost:3306/microservice2?useSSl=false
    username: root
    password: Toor@123456
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: update
        show-sql: true
  application:
    name: DEPARTMENT-SERVICE

#register with eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
